### ISSUE TITLE
Hey Nooaah Need Help !! Urgent

### ISSUE THREAD

**Issue by engrankitjain** [Nooaah/machine-learning-coin-counter-app#1]
@Nooaah 

I am working on a personal project and liked the app implementation you have in your repo.
I am currently getting an error when I am trying to run JUST the server.

I am not trying to run the UI part (Firebase & flutter).

Can you please help to solve the problem in the image ? If you can answer it by today then that will be well appreciated.

![Image 19-10-22 at 8 47 PM](https://user-images.githubusercontent.com/44181074/196853169-adb9a9ee-61bb-4a78-a12f-00be5925d6cf.jpeg)
![Image 19-10-22 at 8 46 PM](https://user-images.githubusercontent.com/44181074/196853174-b566953b-41c4-4e9e-8c01-95e995e7aad4.jpeg)

**Comment by Nooaah** [comment]
Hello,

What's in your _yolov3_training_2400.weights_ ?
Because I see that I put it in the ._gitignore_, and therefore it does not appear in the repo.

**Comment by engrankitjain** [comment]
Hi Nooah,Thanks for your response .I am using the weights from this link .pjreddie.comThis made the program proceed further but then I started getting the error which I shared with you and that is where I need help to solve .Regards,AnkitOn Oct 20, 2022, at 5:06 AM, Noah ***@***.***> wrote:﻿
Hello,
What's in your yolov3_training_2400.weights ?
Because I see that I put it in the .gitignore, and therefore it does not appear in the repo.

**Comment by Nooaah** [comment]
This may be related to newer versions of cv2, can you try replacing it

`self.output_layers = [self.layer_names[i[0] - 1] for i in self.net.getUnconnectedOutLayers()]`

with this

`self.output_layers = [self.layer_names[i - 1] for i in self.net.getUnconnectedOutLayers()]`

**Comment by engrankitjain** [comment]
I have tried the change you suggested but and the response is successful but the total count is 0.0.

I have used the source image as the same image which you have in files_reception

**Comment by engrankitjain** [comment]
This is the output I get

curl -F "file=@/Users/Navneen/EEPHackathon/machine-learning-coin-counter-app/server/src/files_reception/0B2BAEBD.jpg" http://10.0.0.242:5000/send_image

{"calculated_image_path":"http://127.0.0.1:5000/get_image/C234C612.jpg","coins_total":0.0,"execution_time":"0.853"}

**Comment by Nooaah** [comment]
The number is 0.0 because I use my own ._weight_ file : https://bit.ly/3gskO4k, that I trained to recognize french coins. For example, if you use a trained model to recognize animals in this photo with coins, you get nothing.

If you use another model, then you will have to put the right config file _yolov3.cfg_ and _coco.names_ with the right appropriate names.

**Comment by Nooaah** [comment]
For example, when I modify my 3 files:
- yolov3.weights
- yolov3.cfg
- coco.names
(I put them online for you to test: https://bit.ly/3VKhB04)

I get these kind of results very quickly. 👌

<img width="1732" alt="Capture d’écran 2022-10-20 à 15 23 55" src="https://user-images.githubusercontent.com/47362864/196960729-f8ee1d9f-dd87-40e1-955e-112b1ad49597.png">

**Comment by Nooaah** [comment]
> This is the output I get
> 
> curl -F "file=@/Users/Navneen/EEPHackathon/machine-learning-coin-counter-app/server/src/files_reception/0B2BAEBD.jpg" http://10.0.0.242:5000/send_image
> 
> {"calculated_image_path":"[http://127.0.0.1:5000/get_image/C234C612.jpg","coins_total":0.0,"execution_time":"0.853"}](http://127.0.0.1:5000/get_image/C234C612.jpg%22,%22coins_total%22:0.0,%22execution_time%22:%220.853%22%7D)

_coins_total_ in my algorithm is the total cost of coins, not the number of appearances.

**Comment by AdilzhanNS** [comment]
That is very helpful, thanks. Is there a way to train the model for other coins, such as dollars or pounds or maybe there is already trained weights yolo file for those coins that can be used for counting the other coins?

**Comment by Nooaah** [comment]
It's very specific and it requires you to train on Yolo, but here is an overview of the code I made to train my model with my images, which should already be able to help you a lot I think. I did about 2400 iterations to get a correct model, to give you an idea.

https://colab.research.google.com/drive/1D4OADjZCTsAXf9w6fNa5pmjIONzOAVEU?usp=sharing

**Comment by AdilzhanNS** [comment]
Thank a lot, I will have a look! appreciate your prompt replies.

**Comment by Nooaah** [comment]
It's okay, have fun with it 👌

**Comment by engrankitjain** [comment]
Thanks a lot. Noah, learned a lot from your project and really appreciate your prompt response.
